name: release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: fe/package-lock.json

      - name: Install npm dependencies
        run: npm ci
        working-directory: fe

      - name: Build fe
        run: npm run build
        working-directory: fe

      - name: Set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Build static binaries
        run: bash .github/build.sh all

      - name: Gzip build results
        run: gzip share-Go-*

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: share-Go-*.gz
