name: release

on:
  push:
    tags: ["v*"]

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          check-latest: true
          cache: "npm"
          cache-dependency-path: fe/package-lock.json

      - name: Install npm dependencies
        run: npm ci
        working-directory: fe

      - name: Build fe
        run: npm run build
        working-directory: fe

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true

      - name: Build binaries
        run: bash -ex ./build/build.sh all

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*
          generate_release_notes: true
